yarnPath: ".yarn/releases/yarn-berry.cjs"
# nodeLinker: "node-modules"
# Fix for @navikt/ds-css since postcss-cli uses postcss-import as a plugin
packageExtensions:
  postcss-cli@*:
    dependencies:
      postcss-import: "*"
