nodeLinker: node-modules

packageExtensions:
  postcss-cli@*:
    dependencies:
      postcss-import: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
